# -*- coding: utf-8 -*-
"""Step specification, part B: Gate In / Gate Out."""
from spec_a import CH_GATE

W = 413   # standard half-width control

STEPS = [

dict(ch=CH_GATE, screen="s07", title="Open Gate In / Gate Out and Find the Vehicle",
     caption="Gate In / Gate Out vehicle list",
     bullets=[
       "Tap GATE IN/OUT from Quick Links; the default list of all vehicles for your assigned branch is displayed.",
       "Identify the vehicle by QR / VIN barcode scan, Bus Number, Registration Number or VIN, then tap SEARCH.",
       "Verify the Bus Number, Registration Number and VIN, then tap GATE IN against the correct vehicle.",
     ],
     note="Assigned VIN access is controlled by the administrator — only vehicles mapped to your depot are listed.",
     labels={(77,525):("BRANCH — your mapped depot", "L"),
             (623,525):("STATUS — filter by Gate In / Gate Out / All", "R"),
             (78,809):("SEARCH — runs the filter", "L")},
     extra=[
       ("Back arrow", (80,253,92,92), "L"),
       ("GATE IN / GATE OUT — screen title", (226,253,524,96), "L"),
       ("Job card shortcut", (1006,230,120,114), "R"),
       ("Search VIN / Bus No / Reg No — free-text search", (73,646,880,134), "L"),
       ("QR / VIN barcode scanner", (976,646,160,134), "R"),
       ("VIN No. — vehicle identification number", (68,1000,902,74), "L"),
       ("Status badge — the next permitted action", (936,1001,184,64), "R"),
       ("BUS NO. and REG NO. — verify before proceeding", (83,1098,1042,142), "R"),
       ("OPERATIONAL STATUS — vehicle is under maintenance", (76,1260,1050,110), "R"),
       ("GATE IN — records the vehicle's arrival", (100,1723,452,114), "L"),
       ("HOLD — keeps the vehicle pending", (615,1723,452,114), "R"),
       ("Pagination — 10 records per page", (58,2378,1092,112), "L"),
     ]),

dict(ch=CH_GATE, screen="s08", title="Gate In — Bus, Driver and Duty Details",
     caption="Gate In Details — bus identification and duty assignment",
     bullets=[
       "The Bus Details section is filled from the vehicle you selected — verify every value before proceeding.",
       "Tick the Accident checkbox and describe the case if the vehicle has arrived with accident damage.",
       "Under Driver & Duty Information record the driver, badge, duty number, route and performance values.",
     ],
     note="Fields marked with an asterisk are mandatory and must be completed before the entry can be submitted.",
     labels={
       (138,609):("BUS DETAILS — vehicle identification and depot information", "L"),
       (149,918):("DEPOT CODE — auto-filled from your mapped depot", "L"),
       (595,918):("DEPOT NAME", "R"),
       (149,1126):("VIN NO. — vehicle identification number", "L"),
       (595,1126):("BUS NO.", "R"),
       (149,1334):("REGISTRATION NO.", "L"),
       (138,1665):("DRIVER & DUTY INFORMATION — driver details and duty assignment", "R"),
       (149,1931):("DRIVER NAME — select from the list", "L"),
       (595,1931):("BADGE NO.", "R"),
       (149,2139):("DRIVER DUTY NO. (mandatory)", "L"),
       (595,2139):("ROUTE", "R"),
       (149,2347):("DRIVER PERF. 1", "L"),
       (595,2347):("DRIVER PERF. 2", "R"),
     },
     extra=[("ACCIDENT — tick to change the default No to Yes", ("at", r"ACCIDENT", 0, 16), "L")]),

dict(ch=CH_GATE, screen="s09", title="Gate In — Performance, SOC and Journey Details",
     caption="Gate In Details — SOC, shift and journey readings",
     bullets=[
       "Complete the driver performance values and select the SOC In % range.",
       "Tick Breakdown if the vehicle has arrived with a breakdown, then select the Shift.",
       "Journey Details records the system date and time along with the odometer and hour-meter readings.",
     ],
     note="The odometer / hour-meter reading must not be lower than the previously recorded value; a lower reading is rejected.",
     labels={
       (149,633):("DRIVER PERF. 1", "L"),
       (595,633):("DRIVER PERF. 2", "R"),
       (149,841):("SOC IN % — select the 0–100% range", "L"),
       (474,1034):("BREAKDOWN — tick to change the default No to Yes", "L"),
       (149,1211):("SHIFT — the shift receiving the vehicle", "L"),
       (138,1380):("JOURNEY DETAILS — odometer readings and timing information", "R"),
       (149,1689):("SYSTEM DATE — set by the application", "L"),
       (595,1689):("SYSTEM TIME — set by the application", "R"),
       (149,1897):("ODOMETER READING (mandatory)", "L"),
       (595,1897):("HRS — hour-meter reading", "R"),
       (149,2105):("MANUAL DATE", "L"),
       (595,2105):("MANUAL TIME", "R"),
       (149,2313):("FDS STATUS", "L"),
       (149,2521):("SCHEDULE KMS", "L"),
       (595,2521):("KWH/KM (VP1)", "R"),
     }),

dict(ch=CH_GATE, screen="s10", title="Gate In — Schedule, Complaint and Vehicle Status",
     caption="Gate In Details — driver complaint and vehicle status",
     bullets=[
       "Select the FDS Status and enter the Schedule KMS and KWH/KM (VP1) values.",
       "Tick Driver Complaint and record the description in the Remark field, if any.",
       "Set Vehicle Status to Road Worthy or Not Road Worthy, then capture the four wheel temperatures.",
     ],
     labels={
       (149,578):("FDS STATUS — select from the list", "L"),
       (149,778):("SCHEDULE KMS (mandatory)", "L"),
       (595,778):("KWH/KM (VP1)", "R"),
       (474,971):("DRIVER COMPLAINT — tick to change the default No to Yes", "L"),
       (149,1148):("REMARK — description of the complaint", "L"),
       (149,1356):("VEHICLE STATUS — Road Worthy or Not Road Worthy", "L"),
       (138,1525):("VEHICLE CONDITION — wheel temperature status monitoring", "R"),
       (138,2234):("ATTACHMENTS — upload required photos and documents", "R"),
     },
     extra=[
       ("FRONT LEFT wheel temperature", ("below", r"FRONT LEFT", W), "R"),
       ("FRONT RIGHT wheel temperature", ("below", r"FRONT RIGHT", W), "R"),
       ("BACK LEFT wheel temperature", ("below", r"BACK LEFT", W), "R"),
       ("BACK RIGHT wheel temperature", ("below", r"BACK RIGHT", W), "R"),
     ]),

dict(ch=CH_GATE, screen="s11", title="Gate In — Wheel Condition, Attachments and Submit",
     caption="Gate In Details — attachments and submission",
     bullets=[
       "Complete the four wheel temperature readings under Vehicle Condition.",
       "Upload every required photo and document under Attachments.",
       "Verify all mandatory fields, then tap SUBMIT to save the Gate-In entry.",
     ],
     note="On saving a Not Road Worthy entry an auto pre-job card opens with the logged complaints and the vehicle is recorded as Under Maintenance.",
     labels={
       (119,443):("REMARK", "L"),
       (119,623):("VEHICLE STATUS — Road Worthy or Not Road Worthy", "L"),
       (108,762):("VEHICLE CONDITION — wheel temperature status monitoring", "L"),
       (108,1441):("ATTACHMENTS — upload required photos and documents", "R"),
       (384,2333):("SUBMIT — saves the Gate-In transaction", "R"),
     },
     drop=[(136,1664),(136,1890),(616,1890),(136,2109),(616,2109)],
     extra=[
       ("FRONT LEFT wheel temperature", ("below", r"FRONT LEFT", W), "L"),
       ("FRONT RIGHT wheel temperature", ("below", r"FRONT RIGHT", W), "R"),
       ("BACK LEFT wheel temperature", ("below", r"BACK LEFT", W), "L"),
       ("BACK RIGHT wheel temperature", ("below", r"BACK RIGHT", W), "R"),
       ("Driver Duty Slip — mandatory upload", (130,1655,465,190), "L"),
       ("Dashboard Photo — mandatory upload", (610,1655,465,190), "R"),
       ("REAR PHOTO", (130,1882,465,180), "L"),
       ("FRONT PHOTO", (610,1882,465,180), "R"),
       ("LEFT PHOTO", (130,2101,465,180), "L"),
       ("RIGHT PHOTO", (610,2101,465,180), "R"),
     ]),

dict(ch=CH_GATE, screen="s12", title="Gate Out — Select the Vehicle to Release",
     caption="Gate In / Gate Out list showing vehicles eligible for gate-out",
     bullets=[
       "Open the Gate In / Gate Out module and select the Gate-Out option.",
       "Search for the vehicle using Bus Number, Registration Number, VIN or QR scan.",
       "Tap GATE OUT against the vehicle that is to be released.",
     ],
     note="The system allows Gate-Out only for vehicles that have already been gated in and whose job card is closed.",
     labels={(77,525):("BRANCH — your mapped depot", "L"),
             (623,525):("STATUS — filter the list", "R"),
             (78,809):("SEARCH — runs the filter", "L")},
     extra=[
       ("GATE IN / GATE OUT — screen title", (226,253,524,96), "L"),
       ("Search VIN / Bus No / Reg No", (73,646,880,134), "L"),
       ("QR / VIN barcode scanner", (976,646,160,134), "R"),
       ("VIN No. of the gated-in vehicle", (70,1022,900,72), "L"),
       ("GATE OUT badge — the next permitted action", (928,1030,180,58), "R"),
       ("BUS NO. and REG NO.", (90,1120,1040,140), "R"),
       ("GATE IN — not applicable once the vehicle is inside", (100,1295,452,114), "L"),
       ("NEW badge — vehicle not yet gated in", (1013,1496,92,52), "R"),
       ("GATE OUT — opens the Gate Out Details screen", (273,1760,658,114), "R"),
       ("Pagination — 10 records per page", (58,2378,1092,112), "L"),
     ]),

dict(ch=CH_GATE, screen="s13", title="Gate Out — Shift and Journey Details",
     caption="Gate Out Details — journey readings",
     bullets=[
       "Select the Shift under which the vehicle is being released.",
       "Under Journey Details record the odometer reading, HRS, SOC Out % and the manual date and time.",
       "Enter the Schedule KMS, KWH/KM (VP1) and a remark for the transaction.",
     ],
     note="Confirm the gate-out date and time before submitting — the readings are validated against the last Gate-In entry.",
     labels={
       (101,491):("SHIFT — select the releasing shift", "L"),
       (90,720):("JOURNEY DETAILS — odometer readings and timing information", "L"),
       (101,1010):("SYSTEM DATE — set by the application", "L"),
       (635,1010):("SYSTEM TIME — set by the application", "R"),
       (101,1218):("ODOMETER READING (mandatory)", "L"),
       (635,1218):("HRS — hour-meter reading", "R"),
       (101,1426):("SOC OUT % — select the 0–100% range", "L"),
       (101,1634):("MANUAL DATE", "L"),
       (635,1634):("MANUAL TIME", "R"),
       (101,1842):("SCHEDULE KMS", "L"),
       (635,1842):("KWH/KM (VP1)", "R"),
       (101,2050):("REMARK (mandatory)", "L"),
       (90,2279):("VEHICLE CONDITION — wheel temperature status monitoring", "R"),
     }),

dict(ch=CH_GATE, screen="s14", title="Gate Out — Wheel Condition, Attachments and Submit",
     caption="Gate Out Details — attachments and submission",
     bullets=[
       "Complete the four wheel temperature readings under Vehicle Condition.",
       "Upload the required photos and documents under Attachments.",
       "Tap SUBMIT to release the vehicle, or HOLD UP to keep the transaction pending.",
     ],
     note="On confirmation the gate-out entry is submitted and the vehicle is released for out-shedding.",
     labels={
       (90,510):("VEHICLE CONDITION — wheel temperature status monitoring", "L"),
       (90,1303):("ATTACHMENTS — upload required photos and documents", "R"),
       (120,2219):("HOLD UP — keeps the transaction pending", "L"),
       (633,2219):("SUBMIT — releases the vehicle", "R"),
     },
     drop=[(118,1565),(616,1565),(118,1791),(616,1791),(118,2010),(616,2010)],
     extra=[
       ("FRONT LEFT wheel temperature", ("below", r"FRONT LEFT", W), "L"),
       ("FRONT RIGHT wheel temperature", ("below", r"FRONT RIGHT", W), "R"),
       ("BACK LEFT wheel temperature", ("below", r"BACK LEFT", W), "L"),
       ("BACK RIGHT wheel temperature", ("below", r"BACK RIGHT", W), "R"),
       ("Driver Duty Slip — mandatory upload", (112,1556,478,190), "L"),
       ("Dashboard Photo — mandatory upload", (610,1556,478,190), "R"),
       ("REAR PHOTO", (112,1783,478,180), "L"),
       ("FRONT PHOTO", (610,1783,478,180), "R"),
       ("LEFT PHOTO", (112,2002,478,180), "L"),
       ("RIGHT PHOTO", (610,2002,478,180), "R"),
     ]),
]
